# .github/workflows/pull-schema.yml
name: Pull DB Schema

on:
  workflow_dispatch: {}

jobs:
  pull:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sanity check DATABASE_URL
        run: |
          if [ -z "${{ secrets.DATABASE_URL }}" ]; then
            echo "DATABASE_URL secret is missing. Add it in: Settings > Secrets and variables > Actions"
            exit 2
          fi
          echo "DATABASE_URL present. Not printing it because, security."

      - name: Verify function exists (dockerized psql)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          docker run --rm \
            -e DATABASE_URL="$DATABASE_URL" \
            postgres:16-alpine \
            sh -lc 'psql "$DATABASE_URL" -Atc "select count(*) from information_schema.routines where routine_schema=''public'' and routine_name=''get_schema_snapshot'';"' \
          | tee _count.txt
          if [ "$(cat _count.txt)" != "1" ]; then
            echo "Function public.get_schema_snapshot() not found. Did you run Step 1 on THIS Supabase project?"
            exit 3
          fi

      - name: Pull schema JSON (dockerized psql)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          mkdir -p out
          docker run --rm \
            -e DATABASE_URL="$DATABASE_URL" \
            -v "$GITHUB_WORKSPACE/out":/out \
            postgres:16-alpine \
            sh -lc 'psql "$DATABASE_URL" -Atc "select public.get_schema_snapshot()::text;" > /out/schema-lock.raw.json'
          python3 - << 'PY'
import json, sys
with open('out/schema-lock.raw.json','r') as f:
    data = json.loads(f.read())
with open('schema-lock.json','w') as f:
    json.dump(data, f, indent=2)
print('Wrote schema-lock.json')
PY

      - name: Show sample output
        run: |
          head -n 30 schema-lock.json || true

      - name: Commit schema-lock.json
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update schema-lock.json"
          file_pattern: schema-lock.json
